115 comp 상단 navbar
42-Jolly-pingpong/front-end pull request #142
Opened 2023-10-23 06:30 UTC by ebcode2021

## 🌷 Summary

상단 NavBar 기능 구현 완료하였습니다.

## 📢 Description

상단 네비게이션 바에서 파생되는 기능도 전부 구현 완료하였습니다.

모달 : 게임 모드 선택, 매칭 큐
배너 : 게임 신청, 취소
사이드바 : 친구 목록 리스트, 검색, 차단, 삭제 기능

메인페이지 기능 구현 완료하였습니다만, 
추후 애니메이션 기능이 추가될 수 있으므로 domain에서 dev로 merge하지 않고, component만 dev로 merge하도록 하겠습니다.

## 🐙 Related Issue number

-

2023-10-23 07:23 UTC, get6 commented
Assignees에 은선님 추가했어요~

2023-10-23 08:41 UTC, get6 requested changes
수고 많으셨습니다~~

2023-10-23 08:51 UTC, ebcode2021 commented on src/components/button/yellow-button.tsx
> +const YellowButton: React.FC<ButtonProps> = ({ size, children, onClick }) => {
필수로 사이즈를 안넘겨도 되는 option이 있는지 몰랐네요..! 다음번에 작업하겠습니다.

[refactor]
-> 사이즈 필수로 안받아오기

2023-10-23 08:51 UTC, ebcode2021 commented on src/components/friend/sidebar/field/friend-sidebar-search.tsx
> +	const [, setFriendsState] = useRecoilState(friendSidebarListState);
_, 이렇게 할경우에 eslint가 빨간줄로 에러 내더라구요. 그래서 그냥 ,로 비우면 문제없어서 저렇게 했습니당.

2023-10-28 10:21 UTC, minsubro submitted a review, later dismissed

2023-10-28 10:55 UTC, ebcode2021 commented on src/components/friend/sidebar/item/friend-list-empty.tsx
> +HiOutlineUserCircle;
엇 오타입니다. 수정할게요.

2023-10-28 10:57 UTC, minsubro submitted a review, later dismissed

2023-10-28 11:00 UTC, ebcode2021 commented on src/style/default.css
> +	.friend-sidebar {
sidebar관련해서 state관리가 들어가면서, 많이 바뀌어서요! 답변 안드린 것 까지 전부 그쪽에서 수정하겠습니다.

2023-10-28 11:23 UTC, ebcode2021 commented on src/style/default.css
> +	.friend-sidebar {
css가 적용이 안되서 일단 빼뒀는데, 한번 적용해볼게요.

2023-10-28 11:36 UTC, ebcode2021 commented on src/components/friend/sidebar/friend-sidebar-normal.tsx
> +		<>
해결!

2023-10-28 11:36 UTC, ebcode2021 commented on src/components/friend/sidebar/friend-sidebar-empty.tsx
> +		<>
해결!

2023-10-28 11:38 UTC, ebcode2021 commented on src/components/friend/sidebar/friend-sidebar.tsx
> +		return <FriendSidebarEmpty />;
삼항연산자를 써봤는데, 이게 eslint 설정때문에 깔끔한 느낌은 아닌 것 같아서 일단은 if문으로 냅뒀습니다.

2023-10-28 11:40 UTC, ebcode2021 commented on src/components/friend/sidebar/modal/friend-modal.tsx
> +	switch (modalStatus.type) {
확인!

2023-10-28 12:33 UTC, get6 approved these changes
변경 사항 작업하느라 고생 많으셨습니다~~

2023-10-28 12:48 UTC, merged